[platformio]
src_dir = .

[env:genericSTM32F103RC]
platform = ststm32
board = genericSTM32F103RC
upload_protocol = stlink
debug_tool = stlink

board_build.ldscript = CMSIS/STM32F103RC_FLASH.ld

build_flags =
    -D STM32F10X_HD
    -D USE_STDPERIPH_DRIVER
    --specs=nano.specs
    --specs=nosys.specs
    -I USER
    -I CMSIS
    -I FWlib/inc

build_src_filter =
    +<USER/*.c>
    +<FWlib/src/*.c>
    +<CMSIS/system_stm32f10x.c>
    +<CMSIS/startup/startup_stm32f10x_hd.s>
    -<CMSIS/sys.c>

monitor_speed = 9600